---
apiVersion: v1
kind: Pod
metadata: 
  name: excer2
spec:
  containers:
    - name: nginx
      image: nginx
    - name: alpine
      image: alpine
      args:
        - sleep
          1d  
      ports:
        - containerPort: 80          