---
apiVersion: v1
kind: Pod
metadata: 
  name: excer2
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPorts: 80
    - name: alpine
      image: alpine
      args:
        - sleep
          1d       