---
apiVersion: v1
kind: Pod
metadata: 
  name: excer3
spec:
  containers:
    - name: nginx
      image: nginx
    - name: alpine1
      image: alpine
      args:
        - sleep
          1d  
      name: alpine2
      image: alpine
      args:
        - sleep
          10s   
      ports:
        - containerPort: 80     