---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: periodicjob
spec:
  schedule: '* * * * *'
  jobTemplate:
    metadata:
      name: getlivedata
    spec:
      backoffLimit: 2
      restartPolicy: Onfailure    
      template:
        metadata:
          name: livedatapod
      spec:
        containers:
          - name: alpine
            image: alpine
            command:
              - sleep
              - 3s      