---
apiVersion: v1
kind: Pod
metadata:
  name: restartonfailure
spec:.
  restartPolicy: Onfailure
  containers:
    - name: failure
      image: alpain
      args:
        - sleep
        - 3SM       
---
apiVersion: v1
kind: Pod
metadata:
  name: restartonfailure2
spec:.
  restartPolicy: Onfailure
  containers:
    - name: success
      image: alpain
      args:
        - sleep
        - 3s    